# Generated by Django 5.0.1 on 2024-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.CharField(default='12:09', editable=False, max_length=5),
        ),
    ]
